apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sprayproxy
    namespace: pkumari-tenant
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: sprayproxy-metrics-reader
  rules:
  - nonResourceURLs:
    - /metrics
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: sprayproxy-backend-register
  rules:
  - nonResourceURLs:
    - /backends
    verbs:
    - get
    - create
    - delete
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: sprayproxy-backend-register-rolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: sprayproxy-backend-register
  subjects:
  - kind: ServiceAccount
    name: sprayproxy
    namespace: pkumari-tenant
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: rbac-proxy-role
  rules:
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
  - apiGroups:
    - authorization.k8s.io
    resources:
    - subjectaccessreviews
    verbs:
    - create
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: rbac-proxy-rolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rbac-proxy-role
  subjects:
  - kind: ServiceAccount
    name: sprayproxy
    namespace: pkumari-tenant
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/name: sprayproxy
    name: sprayproxy
    namespace: pkumari-tenant
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: sprayproxy
    template:
      metadata:
        labels:
          app.kubernetes.io/name: sprayproxy
      spec:
        containers:
        - args:
          - server
          env:
          - name: SPRAYPROXY_SERVER_BACKEND
          - name: SPRAYPROXY_SERVER_ENABLE_DYNAMIC_BACKENDS
            value: "true"
          image: pkumari-sprayproxy:latest
          name: sprayproxy
          ports:
          - containerPort: 8080
            name: server
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
        - args:
          - --secure-listen-address=0.0.0.0:9443
          - --upstream=http://127.0.0.1:8080/
          - --ignore-paths=/proxy,/healthz
          - --logtostderr=true
          - --v=10
          - --tls-cert-file=/etc/tls/tls.crt
          - --tls-private-key-file=/etc/tls/tls.key
          image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.12
          name: kube-rbac-proxy
          ports:
          - containerPort: 9443
            name: proxy-https
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          volumeMounts:
          - mountPath: /etc/tls
            name: tls
            readOnly: true
        - args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:6000/
          - --logtostderr=true
          - --v=10
          image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.12
          name: kube-rbac-metrics
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
        serviceAccountName: sprayproxy
        volumes:
        - name: tls
          secret:
            defaultMode: 420
            secretName: sprayproxy-tls
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: sprayproxy-tls
    name: sprayproxy-service
    namespace: pkumari-tenant
  spec:
    ports:
    - name: proxy-https
      port: 9443
      protocol: TCP
    selector:
      app.kubernetes.io/name: sprayproxy
- apiVersion: v1
  kind: Service
  metadata:
    name: sprayproxy-metrics-service
    namespace: pkumari-tenant
  spec:
    ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
    selector:
      app.kubernetes.io/name: sprayproxy
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/hsts_header: max-age=63072000
    name: sprayproxy-route
    namespace: pkumari-tenant
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: reencrypt
    to:
      kind: Service
      name: sprayproxy-service
kind: List
---
