apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sprayproxy-myaj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sprayproxy-myaj
    app.kubernetes.io/part-of: sprayproxy
  name: sprayproxy-myaj
spec:
  ports:
  - port: 9443
    targetPort: 9443
  selector:
    app.kubernetes.io/instance: sprayproxy-myaj
status:
  loadBalancer: {}
